#ifndef CONSTANTS_H
#define CONSTANTS_H

typedef enum Type
{
    TYPE_NULL,
    TYPE_BOOL,
    TYPE_INT,
    TYPE_STRING
} Type;

typedef enum NodeType
{
    NODETYPE_LEAF = -1,
    NODETYPE_READ,
    NODETYPE_WRITE,
    NODETYPE_CONNECTOR,
    NODETYPE_OP_ARITHMETIC,
    NODETYPE_OP_ASSIGNMENT,
    NODETYPE_OP_RELATIONAL,
    NODETYPE_IF,
    NODETYPE_WHILE,
    NODETYPE_BREAK,
    NODETYPE_CONTINUE,
    NODETYPE_DO_WHILE,
    NODETYPE_REPEAT_UNTIL,
    NODETYPE_TYPE,
    NODETYPE_DECLARATION,
    NODETYPE_DECLARATION_BLOCK
} NodeType;

#endif